In [4]:
#Importing Python Libraries
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

#Importing the Dataset
dataset = pd.read_csv('D:/Downloads/AE1DS/iris.csv')

#Splitting the Dataset for Train Test Split
X = dataset.iloc[:, 0:4]
Y = dataset.iloc[:, 4]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.35)

#Defining the classifier
classifier = KMeans(n_clusters=3)
classifier.fit(X_train, Y_train)

#Predicting results
y_pred = classifier.predict(X_test)

#Evaluating the model
cfmx = confusion_matrix(Y_test.astype(str), y_pred.astype(str))
print(cfmx)
print(accuracy_score(Y_test, y_pred))

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0 16  0  0  0  0]
 [14  0  1  0  0  0]
 [ 6  0 16  0  0  0]]
0.0
